### PR TITLE
Fix bug in truncate RPC all and add limit for better error message

### LINKED ISSUE #3941: Fix rpc `truncate` leak
### Current Behavior
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-truncate
The truncate rpc is often used when testing, but truncate now has a defect, it will read all the selected blocks into memory at once, when truncate a long chain will be a memory leak and crash

### Expected Behavior

Truncate can be performed in segments

### PR DESCRIPTION
**Pull request by chenyukang**
### What problem does this PR solve?

Fixes #3941

Problem Summary:

- The RPC call has a timeout limitation, so we can not rollback too many blocks, with some testing I found 50000 is a proper limit.
- The iteration on `attached_blocks` is a typo, we can remove it.

### What is changed and how it works?

We add a limit on the number of blocks, if we have a requirement for rollbacking many blocks in one time, we will implement it `cli` mode.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

File: chain/src/chain.rs [hunk 1]
```diff
@@ -279,7 +279,7 @@ impl ChainService {
     }
 
     // Truncate the main chain
-    // Use for testing only
+    // Use for testing only, can only truncate less than 50000 blocks each time
     pub(crate) fn truncate(&mut self, target_tip_hash: &Byte32) -> Result<(), Error> {
         let snapshot = Arc::clone(&self.shared.snapshot());
         assert!(snapshot.is_main_chain(target_tip_hash));
```
Comment (eval-exec) [inline chain/src/chain.rs:285]: I think we shouldn't `assert!` here, it may cause node panic.
If `target_tip_hash` is not in main chain, `fn truncate` should return `Err`.

File: chain/src/chain.rs [hunk 2]
```diff
@@ -299,9 +312,9 @@ impl ChainService {
         db_txn.insert_tip_header(&target_tip_header)?;
         db_txn.insert_current_epoch_ext(&target_epoch_ext)?;
 
-        for blk in fork.attached_blocks() {
-            db_txn.delete_block(blk)?;
-        }
```
Comment (eval-exec) [inline chain/src/chain.rs:304]: I think previous implementation is wrong? Because we expect `target_tip_hash` is on main_chain, so `fork.attached_blocks()` should be empty, is it right?

File: chain/src/chain.rs (hunk 1 above)
Comment (chenyukang) [reply chain/src/chain.rs:285]: I think here is a double-check, custom error message will be given before calling `chain`:

https://github.com/nervosnetwork/ckb/blob/6de945f4512c2781fc17763cbabf1b3e9b580e08/rpc/src/module/test.rs#L497

File: chain/src/chain.rs (hunk 2 above)
Comment (chenyukang) [reply chain/src/chain.rs:304]: yes.

If we want to delete blocks, we should use `for blk in fork.detached_blocks()`, but actually we don't need to delete blocks for testing usage, and even worse if we run `sync` at the same time and there are incoming new blocks, a crash will make the db corrupted.

So, I think it's Ok to remove this part.

Comment (doitian) [reply chain/src/chain.rs:304]: Unrelated to this PR.

**Review by zhangsoledad — APPROVED** [review]
