### PR TITLE
fix: error message on calculate dao max withdraw

### LINKED ISSUE #1389: The error message is not friendly for rpc calculate_dao_maximum_withdraw with invalid outpoint
**Environment**

- **CKB version**: ckb 0.18.0 (rylai-v7 ccc3006c 2019-08-10)
- **Chain**: testnet
- **Operating system**: Windows
- **Arch**: x64
- **Installation**: GitHub Release

**Describe the bug**
1. Send rpc request with invalid outpoint for params (refer to attached file for your reference), it returns error message as: "message": "Internal error", it's not friendly.
image

BTW, there is also error message returned for the ckb node:
image
image

[calculate_dao_maximum_withdraw-req.txt](https://github.com/nervosnetwork/ckb/files/3491378/calculate_dao_maximum_withdraw-req.txt)

### PR DESCRIPTION
**Pull request by driftluo**
fix #1389

before:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error"},"id":2}
```
after:
```
{"jsonrpc":"2.0","error":{"code":-3,"message":"Dao: InvalidOutPoint"},"id":2}
```

### CODE REVIEW

File: error/src/lib.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ pub struct Error {
 impl fmt::Display for Error {
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
         if let Some(cause) = self.cause() {
-            write!(f, "{}({})", self.kind(), cause)
+            write!(f, "{}: {}", self.kind(), cause)
```
Comment (keroro520) [inline error/src/lib.rs]: If you wanna change the style of error messages, please change other error types as well:

```
$ agg 'impl fmt::Display for' | grep Error
2:     2	test/src/rpc/error.rs:9:impl fmt::Display for Error {
10:    10	spec/src/lib.rs:175:impl fmt::Display for SpecLoadError {
11:    11	verification/src/error.rs:237:impl fmt::Display for HeaderError {
12:    12	verification/src/error.rs:247:impl fmt::Display for BlockError {
14:    14	error/src/lib.rs:30:impl fmt::Display for Error {
15:    15	error/src/internal.rs:35:impl fmt::Display for InternalError {
```

Comment (driftluo) [reply error/src/lib.rs]: I think I should use `{:#}` this way to express it instead of directly modifying it.

Other internal errors don't need to be modified, but here, using `{:#}` returns an RPC error

**Comment by doitian** [comment]
bors r=u2,xxuejie,keroro520,doitian

**Comment by driftluo** [comment]
bors retry

**Comment by driftluo** [comment]
bors r=u2,xxuejie,keroro520,doitian,quake,TheWaWaR
