### PR TITLE
Ensure that `block_assembler`'s `Snapshot.tip_number` reaches  `shared.snapshot().tip_number` before `tx_pool.plug_entry`

### LINKED ISSUE #4252: `tests::block_assembler::test_package_multi_best_scores` failed with a probability about `10%`
## Bug Report
`ckb-chain tests::block_assembler::test_package_multi_best_scores` failed with a probability about `10%`

### Current Behavior
```bash
$ while true; do cargo test -p ckb-chain tests::block_assembler::test_package_multi_best_scores -- --nocapture; done     
Finished test [unoptimized + debuginfo] target(s) in 0.13s
     Running unittests src/lib.rs (target/debug/deps/ckb_chain-09dbec27bafb96f0)

running 1 test
thread 'tests::block_assembler::test_package_multi_best_scores' panicked at 'assertion failed: `(left == right)`
  left: `[Byte32(0xcd0d80078c5fb0aed3cc059f73562cb2f1e4a71823f8d720f83ff9f2c9214769), Byte32(0x001d9a4774b77d4d7d4572a52e7f88b267da4b483b1430ee3b1dbe8a555c0ff5), Byte32(0x790691b80c0e6dfca591bf62f72b4b74018ab296d8fc12c1f078397e8e1e2a2b), Byte32(0xf3ace5260c0e0c38b70235466c75645d70ab41d052035d3a636ead24c8c5c935), Byte32(0x42afa370eeb4ef6707a090317bb07740c97d4762c20bfdf114665e7422489524), Byte32(0xa181a0f4a636b91d7efa55ee49b9a42787847242d76c14343cf25eb116d052c2), Byte32(0xe9d809a20bef9c45bdc1258dadb55e7db72b88029b292633e6d748af00f3b6b3), Byte32(0x8006255ad512edfaee5b658424265bef712f49f82d8e4aae072c144232e167d2), Byte32(0xf2bdff1e814a130cf3a76a7e6147ed9c0fd6b367d4be44f1113149cc932b2b0e)]`,
 right: `[Byte32(0xcd0d80078c5fb0aed3cc059f73562cb2f1e4a71823f8d720f83ff9f2c9214769), Byte32(0x001d9a4774b77d4d7d4572a52e7f88b267da4b483b1430ee3b1dbe8a555c0ff5), Byte32(0x790691b80c0e6dfca591bf62f72b4b74018ab296d8fc12c1f078397e8e1e2a2b), Byte32(0xf3ace5260c0e0c38b70235466c75645d70ab41d052035d3a636ead24c8c5c935), Byte32(0x42afa370eeb4ef6707a090317bb07740c97d4762c20bfdf114665e7422489524), Byte32(0xa181a0f4a636b91d7efa55ee49b9a42787847242d76c14343cf25eb116d052c2), Byte32(0xe9d809a20bef9c45bdc1258dadb55e7db72b88029b292633e6d748af00f3b6b3), Byte32(0x8006255ad512edfaee5b658424265bef712f49f82d8e4aae072c144232e167d2), Byte32(0xd551fbc7a1b0f6ef4e1135ce320a562f66b171a1973ba4800e38810e5c618d9d), Byte32(0xf2bdff1e814a130cf3a76a7e6147ed9c0fd6b367d4be44f1113149cc932b2b0e)]`: best scored txs', chain/src/tests/block_assembler.rs:389:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:228:5
   4: ckb_chain::tests::block_assembler::check_txs
             at ./src/tests/block_assembler.rs:389:5
   5: ckb_chain::tests::block_assembler::test_package_multi_best_scores
             at ./src/tests/block_assembler.rs:596:5
   6: ckb_chain::tests::block_assembler::test_package_multi_best_scores::{{closure}}
             at ./src/tests/block_assembler.rs:508:37
   7: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::block_assembler::test_package_multi_best_scores ... FAILED

```

### Environment

- **CKB version**: latest develop branch: [3d674d558e5574f0c77a52798775c903561a933a](https://github.com/nervosnetwork/ckb/tree/3d674d558e5574f0c77a52798775c903561a933a) 
- **Chain**: /
- **Operating system**: `NixOS 24.05 (Uakari) x86_64`
- **Arch**: `Linux Mufasa 6.6.2 #1-NixOS SMP PREEMPT_DYNAMIC Mon Nov 20 10:59:39 UTC 2023 x86_64 GNU/Linux`
- **Installation**: /

### PR DESCRIPTION
**Pull request by eval-exec**
`shared.Snapshot.tip_number` before `tx_pool.plug_entry`

### What problem does this PR solve?
This PR want to fix https://github.com/nervosnetwork/ckb/issues/4252

Issue Number: close #4252 

Problem Summary:

In the `fn test_package_multi_best_scores` function, we generate three blocks in quick succession. This could potentially lead to the `snapshot.tip_number` of the `block_assembler` lagging behind `shared.snapshot.tip_number`.

Consequently, in the `BlockAssembler::calc_dao` function, the following scenario may occur:
The `snapshot.tip_number` is 3, but `calc_dao` is processing a transaction that is packed in block 4. As a result, the transactions in block 4 fail to be resolved.

So, I want to make sure the block_assembler's snapshot.tip_number is larger than shared.snapshot.tip_number before `tx_pool.plug_entry`.

### What is changed and how it works?

What's Changed:

### Related changes

- Wait `block_assembler`'s snapshot.tip_number reach over `shared.snapshot().tip_number()` before executing `tx_pool.plug_entry`

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- None
### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Review by chenyukang — APPROVED** [review]

File: chain/src/tests/block_assembler.rs [hunk 1]
```diff
@@ -557,6 +557,19 @@ fn test_package_multi_best_scores() {
         TxEntry::dummy_resolve(tx3_1.clone(), 0, Capacity::shannons(1000), 1000),
         TxEntry::dummy_resolve(tx4_1.clone(), 0, Capacity::shannons(300), 250),
     ];
+
+    let shared_tip_number = shared.snapshot().tip_number().into();
```
Comment (quake) [inline chain/src/tests/block_assembler.rs:561]: suggest to move this patch block between `plug_entry` and `package_txs`.

Comment (eval-exec) [reply chain/src/tests/block_assembler.rs:561]: If I move this patch block between `plug_entry` and `package_txs`, the error will occur:
```bash
    Finished test [unoptimized + debuginfo] target(s) in 0.22s
     Running unittests src/lib.rs (target/debug/deps/ckb_chain-26e466a4c3646cb7)

running 1 test
thread 'tests::block_assembler::test_package_multi_best_scores' panicked at 'assertion failed: `(left == right)`
  left: `[Byte32(0xcd0d80078c5fb0aed3cc059f73562cb2f1e4a71823f8d720f83ff9f2c9214769), Byte32(0x001d9a4774b77d4d7d4572a52e7f88b267da4b483b1430ee3b1dbe8a555c0ff5), Byte32(0x790691b80c0e6dfca591bf62f72b4b74018ab296d8fc12c1f078397e8e1e2a2b), Byte32(0xf3ace5260c0e0c38b70235466c75645d70ab41d052035d3a636ead24c8c5c935), Byte32(0x42afa370eeb4ef6707a090317bb07740c97d4762c20bfdf114665e7422489524), Byte32(0xa181a0f4a636b91d7efa55ee49b9a42787847242d76c14343cf25eb116d052c2), Byte32(0xe9d809a20bef9c45bdc1258dadb55e7db72b88029b292633e6d748af00f3b6b3), Byte32(0x8006255ad512edfaee5b658424265bef712f49f82d8e4aae072c144232e167d2), Byte32(0xf2bdff1e814a130cf3a76a7e6147ed9c0fd6b367d4be44f1113149cc932b2b0e)]`,
 right: `[Byte32(0xcd0d80078c5fb0aed3cc059f73562cb2f1e4a71823f8d720f83ff9f2c9214769), Byte32(0x001d9a4774b77d4d7d4572a52e7f88b267da4b483b1430ee3b1dbe8a555c0ff5), Byte32(0x790691b80c0e6dfca591bf62f72b4b74018ab296d8fc12c1f078397e8e1e2a2b), Byte32(0xf3ace5260c0e0c38b70235466c75645d70ab41d052035d3a636ead24c8c5c935), Byte32(0x42afa370eeb4ef6707a090317bb07740c97d4762c20bfdf114665e7422489524), Byte32(0xa181a0f4a636b91d7efa55ee49b9a42787847242d76c14343cf25eb116d052c2), Byte32(0xe9d809a20bef9c45bdc1258dadb55e7db72b88029b292633e6d748af00f3b6b3), Byte32(0x8006255ad512edfaee5b658424265bef712f49f82d8e4aae072c144232e167d2), Byte32(0xd551fbc7a1b0f6ef4e1135ce320a562f66b171a1973ba4800e38810e5c618d9d), Byte32(0xf2bdff1e814a130cf3a76a7e6147ed9c0fd6b367d4be44f1113149cc932b2b0e)]`: best scored txs', chain/src/tests/block_assembler.rs:389:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::block_assembler::test_package_multi_best_scores ... FAILED

failures:

failures:
    tests::block_assembler::test_package_multi_best_scores

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 45 filtered out; finished in 0.41s

error: test failed, to rerun pass `-p ckb-chain --lib`

```

**Review by quake — APPROVED** [review]

**Comment by eval-exec** [comment]
CI failed on ubuntu, but no erorr message. https://github.com/nervosnetwork/ckb/actions/runs/7327527043/job/19954521419
