### PR TITLE
terminate miner process when nonce limit reached

### LINKED ISSUE #4062: `ckb miner` doesn't exit when `--limit` flag is specified
### Current Behavior
Start miner by `ckb miner --limit 2`, it doesn't exit after 2 nonces found.
```
$ ckb miner --limit 2
2023-07-06 01:26:52.923 +00:00 main INFO sentry  sentry is disabled
2023-07-06 01:26:52.923 +00:00 main INFO ckb_bin::helper  raise_fd_limit newly-increased limit: 524288
2023-07-06 01:26:52.941 +00:00 main INFO ckb_memory_tracker::process  track current process: disable
2023-07-06 01:26:52.941 +00:00 main INFO ckb_miner::client  loop poll mode: interval 1000ms
Found! #7 0x33c8d9b4861b0bc57edb82fd0b10edd65623ee65acc95c941319e7e8bcd4d3ff
Found! #8 0x9b81f48ebfdf170f1f5e38280f637b926c6f00f5ace7b2d49117818441b68687
Dummy-Worker ⠁ [00:00:00]
2023-07-06 01:27:08.943 +00:00 GlobalRt-3 ERROR ckb_miner::client  notify_new_block error: "SendError(..)"
2023-07-06 01:27:12.944 +00:00 Dummy-Worker ERROR ckb_miner::worker::dummy  nonce_tx send error "SendError(..)"
2023-07-06 01:27:17.944 +00:00 Dummy-Worker ERROR ckb_miner::worker::dummy  nonce_tx send error "SendError(..)"
2023-07-06 01:27:22.944 +00:00 Dummy-Worker ERROR ckb_miner::worker::dummy  nonce_tx send error "SendError(..)"

```

### Expected Behavior
Process exit after specified limit nonces found.
Ref: #1992
### Environment

- **CKB version**: `v0.110.0`
- **Chain**: `dev`
- **Operating system**: `Linux 6.4.0, NixOS, 23.11 (Tapir), 23.11.20230704.78419ed`
- **Arch**: `Linux Mufasa 6.4.0 #1-NixOS SMP PREEMPT_DYNAMIC Sun Jun 25 23:29:58 UTC 2023 x86_64 GNU/Linux`
- **Installation**: GitHub Release

### PR DESCRIPTION
**Pull request by chenyukang**
### What problem does this PR solve?

Issue Number: close #4062

Problem Summary:

### What is changed and how it works?

Proposal: Trivial fix when nonce limitation reached.

What's Changed:

### Related changes

- PR to update `owner/repo`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- Performance regression
- Breaking backward compatibility

### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Review by quake — APPROVED** [review]

**Comment by doitian** [comment]
What's the problem using `break`?

**Comment by eval-exec** [comment]
> What's the problem using `break`?

In `v0.110.0`, when miner reached `limit`, miner will stuck on here: https://github.com/nervosnetwork/ckb/blob/0679b11a3ef855d5f31c1ca569a0037b1e8633de/ckb-bin/src/subcommand/miner.rs#L36

File: miner/src/miner.rs [hunk 1]
```diff
@@ -94,7 +94,8 @@ impl Miner {
                     Ok((pow_hash, work, nonce)) => {
                         self.submit_nonce(pow_hash, work, nonce);
                         if self.limit != 0 && self.nonces_found >= self.limit {
-                            break;
+                            debug!("miner nonce limit reached, terminate ...");
+                            std::process::exit(0);
```
Comment (eval-exec) [inline miner/src/miner.rs:98]: I just replaced `std::process::exit(0)` by `broadcast_exit_signals()` on my local environmentr, miner will exit successfully when `limit` reached.

Comment (eval-exec) [reply miner/src/miner.rs:98]: Adding a cli `bats` test for the miner's `--limit` flag would be an improvement, and it can be done by the example of `ckb run`:
https://github.com/nervosnetwork/ckb/blob/fc9d3e6f17547c0d183c8d1cdfcca56a031c7d08/util/app-config/src/tests/graceful_shutdown.bats#L5-L17

**Review by eval-exec — APPROVED** [review]

**Review by doitian — APPROVED** [review]
