### PR TITLE
Fix error message when sent HTTP GET to RPC

### LINKED ISSUE #4309: Error from RPC on GET request: "Missing request extension: Extension of type `jsonrpc_utils::stream::StreamServerConfig` was not found."
## Bug Report

The following error is received on the RPC when sending a GET request from a browser:

```txt
Missing request extension: Extension of type `jsonrpc_utils::stream::StreamServerConfig` was not found. Perhaps you forgot to add it? See `axum::Extension`.
```
### Expected Behavior

The RPC should return a more appropriate error.

### Environment

- **CKB version**: v0.113.0
- **Operating system**: Ubuntu 20.04
- **Arch**: x64 Linux 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- **Installation**: GitHub Release

### PR DESCRIPTION
**Pull request by chenyukang**
### What problem does this PR solve?

After RPC framework changed, if we sent an GET request to RPC endpoint, the error message has changed to:

```console
Missing request extension: Extension of type `jsonrpc_utils::stream::StreamServerConfig` was not found. Perhaps you forgot to add it? See `axum::Extension`.%
```

Let's keep the same message with the old version.

Issue Number: close #4309

Problem Summary:

### What is changed and how it works?

Add a special handler for RPC endpoint, distinguished from the Websockets configuration.

What's Changed:

### Related changes

- PR to update `owner/repo`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- Performance regression
- Breaking backward compatibility

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

### CODE REVIEW

File: rpc/src/server.rs [hunk 1]
```diff
@@ -90,14 +92,21 @@ impl RpcServer {
             .with_pipeline_size(4);
 
         // HTTP and WS server.
-        let method_router =
-            post(handle_jsonrpc::<Option<Session>>).get(handle_jsonrpc_ws::<Option<Session>>);
+        let post_router = post(handle_jsonrpc::<Option<Session>>);
+        let get_router = if enable_websocket {
+            get(handle_jsonrpc_ws::<Option<Session>>)
```
Comment (eval-exec) [inline rpc/src/server.rs:97]: If `enable_websocket` is set to `true`, will the client side receive the error message `Used HTTP Method is not allowed. POST or OPTIONS is required` when sending a `GET` HTTP request?

Comment (chenyukang) [reply rpc/src/server.rs:97]: no, it's only for HTTP endpoint.
but the error message for Websocket still have a difference, for request like this send to port 28114 (Websocket port):

```console
curl -s -X GET http://127.0.0.1:28114  -H 'Content-Type: application/json' -d '{ "id": 42,   "jsonrpc": "2.0", "method": "get_raw_tx_pool", "params": [] }
```

the old:
```console
WebSocket Protocol Error: Unable to parse WebSocket key.%
```

now:
```console
Connection header did not include 'upgrade'%
```

I think it's not necessary to fix it.

**Review by eval-exec — APPROVED** [review]

**Comment by chenyukang** [comment]
Another weird special issue, maybe we need to compatible with old version,

send request to `ping`, it will always return `pong` as health checkpoint.

```console
curl -s -X GET http://127.0.0.1:8114/ping  -H 'Content-Type: application/json' -d '{ "id": 42,   "jsonrpc": "2.0", "method": "get_raw_tx_pool", "params": [] }'
pong%
```

I add another commit to make new RPC works as before, @eval-exec please re-approve.

**Review by quake — APPROVED** [review]
