### PR TITLE
`get_fee_rate_statistics` should skip first (cellbase) Transaction

### LINKED ISSUE #4646: [BUG] `fee_rate_statistics` returns a feeRate median lower than 1000
Currently `fee_rate_statistics` returns an apparently impossible median feeRate: `0x3b2` (946 < 1000)

To reproduce this feel free to use:

```bash
$ curl -X POST https://rpc.ankr.com/nervos_ckb -d '{"jsonrpc":"2.0","method":"get_fee_rate_statistics","params":[],"id":42}'
{"id":42,"jsonrpc":"2.0","result":{"mean":"0x25580","median":"0x3b2"}}
```

How is this possible?

Love & Peace, Phroi

### PR DESCRIPTION
**Pull request by eval-exec**
### What problem does this PR solve?
Want to fix #4646 and #4350

### Related changes

- get_fee_rate_statistics skip first cellbase in BlockExt

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- None

### Release note 

```release-note
None: Exclude this PR from the release note.
```

### CODE REVIEW

**Comment by phroi** [comment]
Good catch 👍

File: rpc/src/util/fee_rate.rs [hunk 1]
```diff
@@ -87,11 +87,15 @@ where
...
             {
+                // block_ext.txs_fees, cycles, txs_sizes length is same
                 for (fee, cycles, size) in itertools::izip!(
                     block_ext.txs_fees,
                     block_ext.cycles.expect("checked"),
                     block_ext.txs_sizes.expect("checked")
-                ) {
+                )
+                // skip cellbase (first element in the Vec)
+                .skip(1)
```
Comment (quake) [inline rpc/src/util/fee_rate.rs:97]: may better to change line 86 also:
```diff
-            if !block_ext.txs_fees.is_empty()
+            if block_ext.txs_fees.len() > 1
```

Comment (eval-exec) [reply rpc/src/util/fee_rate.rs:97]: Thanks, updated.

**Review by quake — DISMISSED** [review]

**Review by zhangsoledad — APPROVED** [review]

**Comment by eval-exec** [comment]
Fixed the unit test, waiting for CI.

**Review by quake — APPROVED** [review]
